from pydantic import BaseModel, ConfigDict, Field

class Prompt(BaseModel):
    """Data schema representing an inbound natural language instruction or query directed to an AI agent."""
    prompt: str = Field(max_length=500, description="The raw input text or directive submitted by the user. Maximum allowed length is 500 characters.")
    model_config = ConfigDict(from_attributes=True)
    
class Response(BaseModel):
    """Data schema representing the structured execution result or textual response generated by the system."""
    message: str = Field(description="The primary output message or system response text generated in reply to the input prompt.")
    model_config = ConfigDict(from_attributes=True)